### ISSUE TITLE
Set up PYTHONPATH for all subscripts

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/omero-test-infra#4]
See https://github.com/imagej/imagej-omero/commit/fd5a6f03c2e63a33ef6b4fead2d8f2a5ee64d31b

```
+
 +export OMERO_PREFIX=/opt/omero/server/OMERO.server
 +export PYTHONPATH=$OMERO_PREFIX/lib/python
 +
 +python /imagej-omero/.omeroci/create-table.py
```

**Comment by awalter17** [comment]
@joshmoore You don't need the `OMERO_PREFIX` variable. I was just following the documentation [here](https://docs.openmicroscopy.org/omero/5.4.0/developers/Python.html). 

Realistically, if you want to add python support to the omero-server docker container you just need to add
```
export PYTHONPATH=(path_to_your_omero_server)/lib/python
```
to the `Dockerfile` or some `env` file.
